spring.application.name: core-api
spring.profiles.active: local

spring:
  web.resources.add-mappings: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100


---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/coredb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: jonghyun-mysql
      password: jonghyun-mysql
      maximum-pool-size: 100
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

---
spring.config.activate.on-profile: local-dev

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${storage.database.core-db.url}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048


---
spring.config.activate.on-profile: dev

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${storage.database.core-db.url}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

---
spring.config.activate.on-profile: staging

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${storage.database.core-db.url}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

---
spring.config.activate.on-profile: live

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${storage.database.core-db.url}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 25
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
