spring.application.name: core-api
spring.profiles.active: local

spring:
  web.resources.add-mappings: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100
  data:
    redis:
      repositories:
        enabled: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100


---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/coredb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: jonghyun-mysql
      password: jonghyun-mysql
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

---
spring.config.activate.on-profile: local-dev

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: ${spring.data.redis.host:localhost}
      port: ${spring.data.redis.port:6379}
      password: ${spring.data.redis.password:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${storage.database.core-db.url}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048


---
spring.config.activate.on-profile: dev

spring:
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port:6379}
      password: ${spring.data.redis.password:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
          max-wait: -1ms

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${storage.database.core-db.url}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

---
spring.config.activate.on-profile: staging

spring:
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port:6379}
      password: ${spring.data.redis.password:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 15
          max-idle: 15
          min-idle: 3
          max-wait: -1ms

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${storage.database.core-db.url}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

---
spring.config.activate.on-profile: live

spring:
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port:6379}
      password: ${spring.data.redis.password:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 25
          max-idle: 20
          min-idle: 5
          max-wait: -1ms

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${storage.database.core-db.url}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 25
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048